#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source localrc
# Create .localrc for machine specific aliases
if [[ -s ~/.localrc ]]; then
  source ~/.localrc
fi

# Editor
export VISUAL=nano
export EDITOR="$VISUAL"

# cd
alias cdc="cd ~ && clear"

alias projects='cd ~/projects'
alias desktop='cd ~/desktop'
alias dot='cd ~/projects/dotfiles'
alias editBash='nano ~/.bash_profile'
alias editApache='nano /etc/apache2/extra/httpd-vhosts.conf'
alias hideHidden='defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder'
alias showHidden='defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder'
alias addToDock="defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'; killall Dock;"
alias sudop='sudo $(history -p \!\!)'
alias killnode='sudo killall node'
