#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source localrc
# Create .localrc for machine specific aliases
if [[ -s ~/.localrc ]]; then
  source ~/.localrc
fi

# Editor
export VISUAL=nano
export EDITOR="$VISUAL"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# Aliases
alias projects='cd ~/projects'
alias desktop='cd ~/desktop'
alias dot='cd ~/projects/dotfiles'
alias hidehidden='defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder'
alias showhidden='defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder'
alias addtodock="defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'; killall Dock;"
alias sudop='sudo $(history -p \!\!)'
alias killnode='sudo killall node'
alias editzsh='e ~/Projects/dotfiles/zsh/zshrc'
alias editlocal='e ~~/.localrc'
alias agrep='alias | grep $1'
alias gta='git add -N .'
